name: Bug Report
description: Report a bug or unexpected behavior in Authzey
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `npx authzey`
        2. Select '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node -v` and paste the output
      placeholder: "v20.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Windows 11 / macOS 14 / Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots about the issue.
